before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 5

before_install:
- sudo add-apt-repository ppa:jonathonf/ffmpeg-3
- sudo apt update
- sudo apt install ffmpeg

script: mvn clean package && mvn clean install && mvn clean

jdk:
- oraclejdk9
# - openjdk9

language: java
sudo: false
os:
- linux
- windows