before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 5

script: mvn clean package && mvn clean install && mvn clean

jdk:
- oraclejdk9
# - openjdk9

language: java
sudo: false
os:
- linux
- windows